version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname
      - REDIS_URL=redis://redis:6379
    networks:
      - backend

  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_server
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
