version: '3.8'

services:
  python:
    build: .
    container_name: ${BOT_NAME}_app
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - test_uchun

  postgres:
    image: postgres:17
    container_name: ${BOT_NAME}_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - test_uchun

  redis:
    image: redis:latest
    container_name: ${BOT_NAME}_redis
    restart: always
    command: >
      sh -c "sysctl -w vm.overcommit_memory=1 &&
             sysctl -w net.core.somaxconn=65535 &&
             redis-server --maxclients 10000"
    sysctls:
      - net.core.somaxconn=65535
    networks:
      - test_uchun

volumes:
  db_data:

networks:
  test_uchun:
    driver: bridge
